### ISSUE TITLE
[2018-12-02] 使用JavaScript实现SkipList这种数据结构

### ISSUE THREAD

**Issue by dreamapplehappy** [dreamapplehappy/blog#1]
关于这篇文章，大家有什么想法可以在这里提出来

**Comment by kkdev163** [comment]
赞，实现的还是很简洁的。

**Comment by kkdev163** [comment]
对于数据结构的示意图，还有P.ref[level-1]的理解，与您有些出入。。以下是我理解的示意图：
![image](https://p1.music.126.net/FthVnUydWDJ8QATCU1KG8Q==/109951163891902363.jpg)

**Comment by rootdavid** [comment]
```
while(p.refer[i] !== undefined && p.refer[i].data < value) {
		p = p.refer[i];
		// 标记1，此处用于文章的说明
	  }
```
不是很理解p = p.refer[i]，这样不是死循环了吗？

**Comment by mysteryven** [comment]
个人认为 `p.refer[i-1]` 不是指向的下一层节点，而是和 `p.refer[i]` 在同一数组的，只比它 index 小一的节点，也就是你在图中表示的 `p.refer[i-1]` 的下一个节点。

假设我们执行插入操作的 update 数组碰巧都是一竖列那种，也就意味着 update 数组的每一项都是相同的：
```js
newNode[0] = update[0].refer[0]
newNode[1] = update[1].refer[1]
newNode[2] = update[1].refer[2]
...
```
而此时 update[0] === update[1] === update[2]

所以也就意味着`refer[i-1]`不是题主图画的那样呢。

**Comment by HurryOwen** [comment]
![跳表实现示意](https://user-images.githubusercontent.com/18736572/94355727-2125b080-00b9-11eb-887f-3334d4b08b11.png)
